### ISSUE TITLE
Cannot login to tenant UI application

### ISSUE THREAD

**Issue by hosamshahin** [aws-samples/aws-saas-factory-ref-solution-serverless-saas#10] opened 2021-11-07 02:50 UTC
After provisioning a pooled or siloed tenant I got an email with app URL, username, and password. In the app UI when I click on login button I got the following error in the browser console: 

ERROR TypeError: Cannot read property 'usePushedAuthorisationRequests' of null

**Comment by anubhavynr** [comment] 2021-11-11 23:23
Hi, Are you still facing this issue?

I will look into this.

**Comment by anubhavynr** [comment] 2021-11-16 12:57
can you please let us know what version of Angular you are using?

**Comment by anubhavynr** [comment] 2021-11-18 13:57
We were not able to reproduce this so closing for now. Please reopen and provide the version of Angular and Node you are using.

**Closed by anubhavynr** 2021-11-18 13:57 UTC
